### ISSUE TITLE
Exit Source Code Mode

### ISSUE THREAD

**Issue by whippingdot** [adesurirey/typora-notes-dark-theme#17]
**Environment (please complete the following information):**
 - OS: Windows (Newest version)
 - Typora: Version 0.9.98 (Beta)
 - Notes Dark: Latest version (downloaded today)

**Describe the bug**
The bug is that you can't read the text on the `Exit Source Code Mode` button.

**To Reproduce**
Press the source code mode button and look at the exit source code mode button

**Expected behavior**
I expected the text to be clear...

**Screenshots**
![image](https://user-images.githubusercontent.com/64354499/112101359-840d8580-8bcc-11eb-928f-994ba9c7d607.png)

**Comment by christiandmiles** [comment]
This is the missing css

```css
.typora-sourceview-on #toggle-sourceview-btn {
  background-color: var(--bg-color-dark);
}
```

Result:
![image](https://user-images.githubusercontent.com/7004804/112415777-12c3f480-8cea-11eb-9523-ce4ce06ce292.png)
